// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: grpc_timestamps.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AegisType int32

const (
	AegisType_NORMAL AegisType = 0
	AegisType_SINGLE AegisType = 1
)

// Enum value maps for AegisType.
var (
	AegisType_name = map[int32]string{
		0: "NORMAL",
		1: "SINGLE",
	}
	AegisType_value = map[string]int32{
		"NORMAL": 0,
		"SINGLE": 1,
	}
)

func (x AegisType) Enum() *AegisType {
	p := new(AegisType)
	*p = x
	return p
}

func (x AegisType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AegisType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_timestamps_proto_enumTypes[0].Descriptor()
}

func (AegisType) Type() protoreflect.EnumType {
	return &file_grpc_timestamps_proto_enumTypes[0]
}

func (x AegisType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AegisType.Descriptor instead.
func (AegisType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{0}
}

type Phrase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Phrase   string                 `protobuf:"bytes,3,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Duration string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Type     string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Phrase) Reset() {
	*x = Phrase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phrase) ProtoMessage() {}

func (x *Phrase) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phrase.ProtoReflect.Descriptor instead.
func (*Phrase) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{0}
}

func (x *Phrase) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Phrase) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Phrase) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *Phrase) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Phrase) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RemovePhrase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Phrase string                 `protobuf:"bytes,2,opt,name=phrase,proto3" json:"phrase,omitempty"`
}

func (x *RemovePhrase) Reset() {
	*x = RemovePhrase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePhrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePhrase) ProtoMessage() {}

func (x *RemovePhrase) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePhrase.ProtoReflect.Descriptor instead.
func (*RemovePhrase) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{1}
}

func (x *RemovePhrase) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RemovePhrase) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

type Nuke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Type     string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Duration string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Word     string                 `protobuf:"bytes,4,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Nuke) Reset() {
	*x = Nuke{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nuke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nuke) ProtoMessage() {}

func (x *Nuke) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nuke.ProtoReflect.Descriptor instead.
func (*Nuke) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{2}
}

func (x *Nuke) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Nuke) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Nuke) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Nuke) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type Aegis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Type AegisType              `protobuf:"varint,2,opt,name=type,proto3,enum=grpc_timestamps.AegisType" json:"type,omitempty"`
	Word string                 `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Aegis) Reset() {
	*x = Aegis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aegis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aegis) ProtoMessage() {}

func (x *Aegis) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aegis.ProtoReflect.Descriptor instead.
func (*Aegis) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{3}
}

func (x *Aegis) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Aegis) GetType() AegisType {
	if x != nil {
		return x.Type
	}
	return AegisType_NORMAL
}

func (x *Aegis) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type Mutelinks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Status   string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Duration string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	User     string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Mutelinks) Reset() {
	*x = Mutelinks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutelinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutelinks) ProtoMessage() {}

func (x *Mutelinks) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutelinks.ProtoReflect.Descriptor instead.
func (*Mutelinks) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{4}
}

func (x *Mutelinks) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Mutelinks) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Mutelinks) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Mutelinks) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_timestamps_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_timestamps_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_timestamps_proto_rawDescGZIP(), []int{5}
}

var File_grpc_timestamps_proto protoreflect.FileDescriptor

var file_grpc_timestamps_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x50, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x72, 0x61,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65,
	0x22, 0x7a, 0x0a, 0x04, 0x4e, 0x75, 0x6b, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x7b, 0x0a, 0x05,
	0x41, 0x65, 0x67, 0x69, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x41, 0x65, 0x67, 0x69, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x4d, 0x75,
	0x74, 0x65, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x23, 0x0a, 0x09, 0x41, 0x65, 0x67, 0x69,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x32, 0xe8, 0x02,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4e, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12,
	0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x1a, 0x16,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x50, 0x68, 0x72, 0x61,
	0x73, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4e, 0x75, 0x6b, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x4e, 0x75,
	0x6b, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0c,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x41, 0x65, 0x67, 0x69, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x41,
	0x65, 0x67, 0x69, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x48,
	0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x75, 0x74, 0x65, 0x6c, 0x69, 0x6e,
	0x6b, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x2e, 0x4d, 0x75, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x1a, 0x16,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_timestamps_proto_rawDescOnce sync.Once
	file_grpc_timestamps_proto_rawDescData = file_grpc_timestamps_proto_rawDesc
)

func file_grpc_timestamps_proto_rawDescGZIP() []byte {
	file_grpc_timestamps_proto_rawDescOnce.Do(func() {
		file_grpc_timestamps_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_timestamps_proto_rawDescData)
	})
	return file_grpc_timestamps_proto_rawDescData
}

var file_grpc_timestamps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_timestamps_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_timestamps_proto_goTypes = []interface{}{
	(AegisType)(0),                // 0: grpc_timestamps.AegisType
	(*Phrase)(nil),                // 1: grpc_timestamps.Phrase
	(*RemovePhrase)(nil),          // 2: grpc_timestamps.RemovePhrase
	(*Nuke)(nil),                  // 3: grpc_timestamps.Nuke
	(*Aegis)(nil),                 // 4: grpc_timestamps.Aegis
	(*Mutelinks)(nil),             // 5: grpc_timestamps.Mutelinks
	(*Empty)(nil),                 // 6: grpc_timestamps.Empty
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_grpc_timestamps_proto_depIdxs = []int32{
	7,  // 0: grpc_timestamps.Phrase.time:type_name -> google.protobuf.Timestamp
	7,  // 1: grpc_timestamps.RemovePhrase.time:type_name -> google.protobuf.Timestamp
	7,  // 2: grpc_timestamps.Nuke.time:type_name -> google.protobuf.Timestamp
	7,  // 3: grpc_timestamps.Aegis.time:type_name -> google.protobuf.Timestamp
	0,  // 4: grpc_timestamps.Aegis.type:type_name -> grpc_timestamps.AegisType
	7,  // 5: grpc_timestamps.Mutelinks.time:type_name -> google.protobuf.Timestamp
	2,  // 6: grpc_timestamps.Status.ReceiveRemovePhrase:input_type -> grpc_timestamps.RemovePhrase
	1,  // 7: grpc_timestamps.Status.ReceivePhrase:input_type -> grpc_timestamps.Phrase
	3,  // 8: grpc_timestamps.Status.ReceiveNuke:input_type -> grpc_timestamps.Nuke
	4,  // 9: grpc_timestamps.Status.ReceiveAegis:input_type -> grpc_timestamps.Aegis
	5,  // 10: grpc_timestamps.Status.ReceiveMutelinks:input_type -> grpc_timestamps.Mutelinks
	6,  // 11: grpc_timestamps.Status.ReceiveRemovePhrase:output_type -> grpc_timestamps.Empty
	6,  // 12: grpc_timestamps.Status.ReceivePhrase:output_type -> grpc_timestamps.Empty
	6,  // 13: grpc_timestamps.Status.ReceiveNuke:output_type -> grpc_timestamps.Empty
	6,  // 14: grpc_timestamps.Status.ReceiveAegis:output_type -> grpc_timestamps.Empty
	6,  // 15: grpc_timestamps.Status.ReceiveMutelinks:output_type -> grpc_timestamps.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_grpc_timestamps_proto_init() }
func file_grpc_timestamps_proto_init() {
	if File_grpc_timestamps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_timestamps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phrase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_timestamps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePhrase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_timestamps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nuke); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_timestamps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aegis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_timestamps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutelinks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_timestamps_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_timestamps_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_timestamps_proto_goTypes,
		DependencyIndexes: file_grpc_timestamps_proto_depIdxs,
		EnumInfos:         file_grpc_timestamps_proto_enumTypes,
		MessageInfos:      file_grpc_timestamps_proto_msgTypes,
	}.Build()
	File_grpc_timestamps_proto = out.File
	file_grpc_timestamps_proto_rawDesc = nil
	file_grpc_timestamps_proto_goTypes = nil
	file_grpc_timestamps_proto_depIdxs = nil
}
